apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-auto-tuned
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/shmador/go-kubernetes-tuner'
    targetRevision: HEAD
    path: charts/nginx

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

