name: Validate Helm & Go

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Helm chart
      run: helm lint charts/nginx
    - name: Run Go tests
      run: go test ./tuner
